name: Build Jekyll for GitHub Pages

on:
  push:
    branches:
      - main  # Replace this with the name of your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Build Jekyll for GitHub Pages
      uses: actions/jekyll-build-pages@v1.0.7
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

- name: Build Jekyll for GitHub Pages
  uses: actions/jekyll-build-pages@v1.0.7
